version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: node:10.13.0
    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Build
          command: yarn build
      - run:
          name: Check Dist
          command: ls -la dist
      -  save_cache:
           paths:
             - ~/workspace/node_modules
           key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: . # workspaceのrootをworking_directoryからの相対パスで指定
          paths:
            - . # 共有するパスをworking_direcrotyからの相対パスで指定
  test:
    working_directory: ~/workspace
    docker:
      - image: node:10.13.0
    steps:
      - attach_workspace: # workspaceをアタッチする
          at: .
      - run:
         name: Test
         command: yarn test
  deploy:
    working_directory: ~/workspace
    docker:
      - image: node:10.13.0
    steps:
      - attach_workspace:
          at: .
      - deploy:
          command: echo Deploy!
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:  # buildが成功したらtestを実行する
            - build
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
