version: 2
jobs:
  build:
    docker:
      - image: node:10.13.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Build
          command: yarn build
      - run:
          name: Check Dist
          command: ls -la dist
